apiVersion: apps/v1 
kind: Deployment
metadata:
  name: green 
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 2  
  template: 
    metadata: 
      name: green
      labels:
        app: green
    spec:
      containers: 
        - name: hello
          image: mylandmarktech/hello:4   
          ports: 
          - containerPort: 80
