apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: myapp
  labels:
    app: fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tesla
  template:
    metadata:
      name: app
      labels:
        app: tesla
    spec:
      containers:
      - name: springapp
        image: dockerhandson/spring-boot-mongo
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123
        - name: MONGO_DB_HOSTNAME
          value: mongo
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: springapp
spec:
  selector:
    app: tesla
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort
